### PR TITLE
Fix build with Boost 1.85.0

### PR DESCRIPTION
**Pull request by cho-m**
Building with Boost 1.85.0 was failing with:
```
In file included from /tmp/standardese-20240425-46817-wfmhlb/tool/main.cpp:11:
/tmp/standardese-20240425-46817-wfmhlb/tool/filesystem.hpp:101:26: error: no member named 'no_push' in 'boost::filesystem::recursive_directory_iterator'
                    iter.no_push();
                    ~~~~ ^
In file included from /tmp/standardese-20240425-46817-wfmhlb/tool/generator.cpp:5:
In file included from /tmp/standardese-20240425-46817-wfmhlb/tool/generator.hpp:20:
/tmp/standardese-20240425-46817-wfmhlb/tool/filesystem.hpp:101:26: error: no member named 'no_push' in 'boost::filesystem::recursive_directory_iterator'
                    iter.no_push();
                    ~~~~ ^
1 error generated.
```

https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html shows that `no_push()` is a removed API with a direct replacement of `disable_recursion_pending()`.

### CODE REVIEW

**Comment by saraedum** [comment]
The CI errors are unrelated.

clang 18 reports the `extern "C"` differently than before but cppast does not handle the `CXCursor_LinkageSpec` correctly so we print a warning message. We should just ignore warning with the two failing tests as a quick fix.

Also with clang 18, `f(const foo&<T>)` is now not reported as `f(foo<T> const&)` anymore.

**Comment by saraedum** [comment]
Seems to work fine with Boost 1.85 now. Thanks @cho-m!
